process: migrate
	@yarn processor:debug


serve:
	@yarn server:start


migrate:
	@yarn db:migrate


migration:
	@yarn squid-typeorm-migration-generate


build:
	@yarn build


codegen:
	@yarn squid-typeorm-codegen


typegen-parachain:
	@yarn squid-substrate-typegen ./typegen/typegen-parachain.dev.json