versions-testnet:
	@npx squid-substrate-metadata-explorer --chain wss://avn.test.aventus.io --archive http://localhost:4444/graphql --out ./versions.testnet.jsonl

versions-parachain-dev:
	@npx squid-substrate-metadata-explorer --chain wss://avn-parachain.dev.aventus.io --archive http://localhost:4444/graphql --out ./versions-parachain.dev.jsonl
